version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.prod
        volumes:
            - .:/app
        ports:
            - "8009:80"
        environment:
            - SQLALCHEMY_DATABASE_URI=postgresql://admin_diabetes:admin_diabetes@db:5432/application
        depends_on:
            - db
    db:
        image: postgres
        volumes:
            - diabetes-tc2:/var/lib/postgresql/data/
        expose:
            - 5432
        environment:
            - POSTGRES_USER=admin_diabetes
            - POSTGRES_PASSWORD=admin_diabetes
            - POSTGRES_DB=application

volumes:
  diabetes-tc2: